version: "3"
services:
  jupyterlab:
    build:
      context: .
    user: root
    ports:
      - "8888:8888"
    volumes:
      - "./work:/home/jovyan/work"
    environment:
      NB_UID: $UID
      GRANT_SUDO: "yes"
    command: start.sh jupyter lab --NotebookApp.token=''

